/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsContactsRouteRouteImport } from './routes/settings/contacts/route'
import { Route as SettingsOrganizationsRouteRouteImport } from './routes/settings/organizations/route'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsContactsIndexRouteImport } from './routes/settings/contacts/index'
import { Route as SettingsContactsAttributesRouteImport } from './routes/settings/contacts/attributes'
import { Route as SettingsContactsViewsRouteImport } from './routes/settings/contacts/views'
import { Route as SettingsOrganizationsIndexRouteImport } from './routes/settings/organizations/index'
import { Route as SettingsOrganizationsAttributesRouteImport } from './routes/settings/organizations/attributes'
import { Route as SettingsOrganizationsViewsRouteImport } from './routes/settings/organizations/views'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsContactsRouteRoute = SettingsContactsRouteRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsOrganizationsRouteRoute =
  SettingsOrganizationsRouteRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsContactsIndexRoute = SettingsContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsContactsRouteRoute,
} as any)
const SettingsContactsAttributesRoute =
  SettingsContactsAttributesRouteImport.update({
    id: '/attributes',
    path: '/attributes',
    getParentRoute: () => SettingsContactsRouteRoute,
  } as any)
const SettingsContactsViewsRoute = SettingsContactsViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => SettingsContactsRouteRoute,
} as any)
const SettingsOrganizationsIndexRoute =
  SettingsOrganizationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsOrganizationsRouteRoute,
  } as any)
const SettingsOrganizationsAttributesRoute =
  SettingsOrganizationsAttributesRouteImport.update({
    id: '/attributes',
    path: '/attributes',
    getParentRoute: () => SettingsOrganizationsRouteRoute,
  } as any)
const SettingsOrganizationsViewsRoute =
  SettingsOrganizationsViewsRouteImport.update({
    id: '/views',
    path: '/views',
    getParentRoute: () => SettingsOrganizationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/follow-ups': typeof FollowUpsRoute
  '/organizations': typeof OrganizationsRoute
  '/settings/contacts': typeof SettingsContactsRouteRouteWithChildren
  '/settings/organizations': typeof SettingsOrganizationsRouteRouteWithChildren
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/contacts/attributes': typeof SettingsContactsAttributesRoute
  '/settings/contacts/views': typeof SettingsContactsViewsRoute
  '/settings/organizations/attributes': typeof SettingsOrganizationsAttributesRoute
  '/settings/organizations/views': typeof SettingsOrganizationsViewsRoute
  '/settings/contacts/': typeof SettingsContactsIndexRoute
  '/settings/organizations/': typeof SettingsOrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/follow-ups': typeof FollowUpsRoute
  '/organizations': typeof OrganizationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/contacts/attributes': typeof SettingsContactsAttributesRoute
  '/settings/contacts/views': typeof SettingsContactsViewsRoute
  '/settings/organizations/attributes': typeof SettingsOrganizationsAttributesRoute
  '/settings/organizations/views': typeof SettingsOrganizationsViewsRoute
  '/settings/contacts': typeof SettingsContactsIndexRoute
  '/settings/organizations': typeof SettingsOrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/follow-ups': typeof FollowUpsRoute
  '/organizations': typeof OrganizationsRoute
  '/settings/contacts': typeof SettingsContactsRouteRouteWithChildren
  '/settings/organizations': typeof SettingsOrganizationsRouteRouteWithChildren
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/contacts/attributes': typeof SettingsContactsAttributesRoute
  '/settings/contacts/views': typeof SettingsContactsViewsRoute
  '/settings/organizations/attributes': typeof SettingsOrganizationsAttributesRoute
  '/settings/organizations/views': typeof SettingsOrganizationsViewsRoute
  '/settings/contacts/': typeof SettingsContactsIndexRoute
  '/settings/organizations/': typeof SettingsOrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/contacts'
    | '/follow-ups'
    | '/organizations'
    | '/settings/contacts'
    | '/settings/organizations'
    | '/settings/profile'
    | '/settings/'
    | '/settings/contacts/attributes'
    | '/settings/contacts/views'
    | '/settings/organizations/attributes'
    | '/settings/organizations/views'
    | '/settings/contacts/'
    | '/settings/organizations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/follow-ups'
    | '/organizations'
    | '/settings/profile'
    | '/settings'
    | '/settings/contacts/attributes'
    | '/settings/contacts/views'
    | '/settings/organizations/attributes'
    | '/settings/organizations/views'
    | '/settings/contacts'
    | '/settings/organizations'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/contacts'
    | '/follow-ups'
    | '/organizations'
    | '/settings/contacts'
    | '/settings/organizations'
    | '/settings/profile'
    | '/settings/'
    | '/settings/contacts/attributes'
    | '/settings/contacts/views'
    | '/settings/organizations/attributes'
    | '/settings/organizations/views'
    | '/settings/contacts/'
    | '/settings/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  FollowUpsRoute: typeof FollowUpsRoute
  OrganizationsRoute: typeof OrganizationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/contacts': {
      id: '/settings/contacts'
      path: '/contacts'
      fullPath: '/settings/contacts'
      preLoaderRoute: typeof SettingsContactsRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/organizations': {
      id: '/settings/organizations'
      path: '/organizations'
      fullPath: '/settings/organizations'
      preLoaderRoute: typeof SettingsOrganizationsRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/contacts/': {
      id: '/settings/contacts/'
      path: '/'
      fullPath: '/settings/contacts/'
      preLoaderRoute: typeof SettingsContactsIndexRouteImport
      parentRoute: typeof SettingsContactsRouteRoute
    }
    '/settings/contacts/attributes': {
      id: '/settings/contacts/attributes'
      path: '/attributes'
      fullPath: '/settings/contacts/attributes'
      preLoaderRoute: typeof SettingsContactsAttributesRouteImport
      parentRoute: typeof SettingsContactsRouteRoute
    }
    '/settings/contacts/views': {
      id: '/settings/contacts/views'
      path: '/views'
      fullPath: '/settings/contacts/views'
      preLoaderRoute: typeof SettingsContactsViewsRouteImport
      parentRoute: typeof SettingsContactsRouteRoute
    }
    '/settings/organizations/': {
      id: '/settings/organizations/'
      path: '/'
      fullPath: '/settings/organizations/'
      preLoaderRoute: typeof SettingsOrganizationsIndexRouteImport
      parentRoute: typeof SettingsOrganizationsRouteRoute
    }
    '/settings/organizations/attributes': {
      id: '/settings/organizations/attributes'
      path: '/attributes'
      fullPath: '/settings/organizations/attributes'
      preLoaderRoute: typeof SettingsOrganizationsAttributesRouteImport
      parentRoute: typeof SettingsOrganizationsRouteRoute
    }
    '/settings/organizations/views': {
      id: '/settings/organizations/views'
      path: '/views'
      fullPath: '/settings/organizations/views'
      preLoaderRoute: typeof SettingsOrganizationsViewsRouteImport
      parentRoute: typeof SettingsOrganizationsRouteRoute
    }
  }
}

interface SettingsContactsRouteRouteChildren {
  SettingsContactsAttributesRoute: typeof SettingsContactsAttributesRoute
  SettingsContactsViewsRoute: typeof SettingsContactsViewsRoute
  SettingsContactsIndexRoute: typeof SettingsContactsIndexRoute
}

const SettingsContactsRouteRouteChildren: SettingsContactsRouteRouteChildren = {
  SettingsContactsAttributesRoute: SettingsContactsAttributesRoute,
  SettingsContactsViewsRoute: SettingsContactsViewsRoute,
  SettingsContactsIndexRoute: SettingsContactsIndexRoute,
}

const SettingsContactsRouteRouteWithChildren =
  SettingsContactsRouteRoute._addFileChildren(
    SettingsContactsRouteRouteChildren,
  )

interface SettingsOrganizationsRouteRouteChildren {
  SettingsOrganizationsAttributesRoute: typeof SettingsOrganizationsAttributesRoute
  SettingsOrganizationsViewsRoute: typeof SettingsOrganizationsViewsRoute
  SettingsOrganizationsIndexRoute: typeof SettingsOrganizationsIndexRoute
}

const SettingsOrganizationsRouteRouteChildren: SettingsOrganizationsRouteRouteChildren =
  {
    SettingsOrganizationsAttributesRoute: SettingsOrganizationsAttributesRoute,
    SettingsOrganizationsViewsRoute: SettingsOrganizationsViewsRoute,
    SettingsOrganizationsIndexRoute: SettingsOrganizationsIndexRoute,
  }

const SettingsOrganizationsRouteRouteWithChildren =
  SettingsOrganizationsRouteRoute._addFileChildren(
    SettingsOrganizationsRouteRouteChildren,
  )

interface SettingsRouteRouteChildren {
  SettingsContactsRouteRoute: typeof SettingsContactsRouteRouteWithChildren
  SettingsOrganizationsRouteRoute: typeof SettingsOrganizationsRouteRouteWithChildren
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsContactsRouteRoute: SettingsContactsRouteRouteWithChildren,
  SettingsOrganizationsRouteRoute: SettingsOrganizationsRouteRouteWithChildren,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ContactsRoute: ContactsRoute,
  FollowUpsRoute: FollowUpsRoute,
  OrganizationsRoute: OrganizationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
