/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactsRouteRouteImport } from './routes/contacts/route'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as OrganizationsRouteRouteImport } from './routes/organizations/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as ContactsIdRouteImport } from './routes/contacts/$id'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as OrganizationsIdRouteImport } from './routes/organizations/$id'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsContactsRouteRouteImport } from './routes/settings/contacts/route'
import { Route as SettingsOrganizationsRouteRouteImport } from './routes/settings/organizations/route'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsContactsIndexRouteImport } from './routes/settings/contacts/index'
import { Route as SettingsContactsAttributesRouteImport } from './routes/settings/contacts/attributes'
import { Route as SettingsContactsViewsRouteImport } from './routes/settings/contacts/views'
import { Route as SettingsOrganizationsIndexRouteImport } from './routes/settings/organizations/index'
import { Route as SettingsOrganizationsAttributesRouteImport } from './routes/settings/organizations/attributes'
import { Route as SettingsOrganizationsViewsRouteImport } from './routes/settings/organizations/views'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRouteRoute = ContactsRouteRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRouteRoute = OrganizationsRouteRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContactsRouteRoute,
} as any)
const ContactsIdRoute = ContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContactsRouteRoute,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationsRouteRoute,
} as any)
const OrganizationsIdRoute = OrganizationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrganizationsRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsContactsRouteRoute = SettingsContactsRouteRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsOrganizationsRouteRoute =
  SettingsOrganizationsRouteRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsContactsIndexRoute = SettingsContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsContactsRouteRoute,
} as any)
const SettingsContactsAttributesRoute =
  SettingsContactsAttributesRouteImport.update({
    id: '/attributes',
    path: '/attributes',
    getParentRoute: () => SettingsContactsRouteRoute,
  } as any)
const SettingsContactsViewsRoute = SettingsContactsViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => SettingsContactsRouteRoute,
} as any)
const SettingsOrganizationsIndexRoute =
  SettingsOrganizationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsOrganizationsRouteRoute,
  } as any)
const SettingsOrganizationsAttributesRoute =
  SettingsOrganizationsAttributesRouteImport.update({
    id: '/attributes',
    path: '/attributes',
    getParentRoute: () => SettingsOrganizationsRouteRoute,
  } as any)
const SettingsOrganizationsViewsRoute =
  SettingsOrganizationsViewsRouteImport.update({
    id: '/views',
    path: '/views',
    getParentRoute: () => SettingsOrganizationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRouteRouteWithChildren
  '/organizations': typeof OrganizationsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/follow-ups': typeof FollowUpsRoute
  '/settings/contacts': typeof SettingsContactsRouteRouteWithChildren
  '/settings/organizations': typeof SettingsOrganizationsRouteRouteWithChildren
  '/contacts/$id': typeof ContactsIdRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/contacts/': typeof ContactsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/contacts/attributes': typeof SettingsContactsAttributesRoute
  '/settings/contacts/views': typeof SettingsContactsViewsRoute
  '/settings/organizations/attributes': typeof SettingsOrganizationsAttributesRoute
  '/settings/organizations/views': typeof SettingsOrganizationsViewsRoute
  '/settings/contacts/': typeof SettingsContactsIndexRoute
  '/settings/organizations/': typeof SettingsOrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/follow-ups': typeof FollowUpsRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/contacts': typeof ContactsIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/contacts/attributes': typeof SettingsContactsAttributesRoute
  '/settings/contacts/views': typeof SettingsContactsViewsRoute
  '/settings/organizations/attributes': typeof SettingsOrganizationsAttributesRoute
  '/settings/organizations/views': typeof SettingsOrganizationsViewsRoute
  '/settings/contacts': typeof SettingsContactsIndexRoute
  '/settings/organizations': typeof SettingsOrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRouteRouteWithChildren
  '/organizations': typeof OrganizationsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/follow-ups': typeof FollowUpsRoute
  '/settings/contacts': typeof SettingsContactsRouteRouteWithChildren
  '/settings/organizations': typeof SettingsOrganizationsRouteRouteWithChildren
  '/contacts/$id': typeof ContactsIdRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/contacts/': typeof ContactsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/contacts/attributes': typeof SettingsContactsAttributesRoute
  '/settings/contacts/views': typeof SettingsContactsViewsRoute
  '/settings/organizations/attributes': typeof SettingsOrganizationsAttributesRoute
  '/settings/organizations/views': typeof SettingsOrganizationsViewsRoute
  '/settings/contacts/': typeof SettingsContactsIndexRoute
  '/settings/organizations/': typeof SettingsOrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/organizations'
    | '/settings'
    | '/follow-ups'
    | '/settings/contacts'
    | '/settings/organizations'
    | '/contacts/$id'
    | '/organizations/$id'
    | '/settings/profile'
    | '/contacts/'
    | '/organizations/'
    | '/settings/'
    | '/settings/contacts/attributes'
    | '/settings/contacts/views'
    | '/settings/organizations/attributes'
    | '/settings/organizations/views'
    | '/settings/contacts/'
    | '/settings/organizations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/follow-ups'
    | '/contacts/$id'
    | '/organizations/$id'
    | '/settings/profile'
    | '/contacts'
    | '/organizations'
    | '/settings'
    | '/settings/contacts/attributes'
    | '/settings/contacts/views'
    | '/settings/organizations/attributes'
    | '/settings/organizations/views'
    | '/settings/contacts'
    | '/settings/organizations'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/organizations'
    | '/settings'
    | '/follow-ups'
    | '/settings/contacts'
    | '/settings/organizations'
    | '/contacts/$id'
    | '/organizations/$id'
    | '/settings/profile'
    | '/contacts/'
    | '/organizations/'
    | '/settings/'
    | '/settings/contacts/attributes'
    | '/settings/contacts/views'
    | '/settings/organizations/attributes'
    | '/settings/organizations/views'
    | '/settings/contacts/'
    | '/settings/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRouteRoute: typeof ContactsRouteRouteWithChildren
  OrganizationsRouteRoute: typeof OrganizationsRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  FollowUpsRoute: typeof FollowUpsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof ContactsRouteRoute
    }
    '/contacts/$id': {
      id: '/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ContactsIdRouteImport
      parentRoute: typeof ContactsRouteRoute
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof OrganizationsRouteRoute
    }
    '/organizations/$id': {
      id: '/organizations/$id'
      path: '/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof OrganizationsIdRouteImport
      parentRoute: typeof OrganizationsRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/contacts': {
      id: '/settings/contacts'
      path: '/contacts'
      fullPath: '/settings/contacts'
      preLoaderRoute: typeof SettingsContactsRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/organizations': {
      id: '/settings/organizations'
      path: '/organizations'
      fullPath: '/settings/organizations'
      preLoaderRoute: typeof SettingsOrganizationsRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/contacts/': {
      id: '/settings/contacts/'
      path: '/'
      fullPath: '/settings/contacts/'
      preLoaderRoute: typeof SettingsContactsIndexRouteImport
      parentRoute: typeof SettingsContactsRouteRoute
    }
    '/settings/contacts/attributes': {
      id: '/settings/contacts/attributes'
      path: '/attributes'
      fullPath: '/settings/contacts/attributes'
      preLoaderRoute: typeof SettingsContactsAttributesRouteImport
      parentRoute: typeof SettingsContactsRouteRoute
    }
    '/settings/contacts/views': {
      id: '/settings/contacts/views'
      path: '/views'
      fullPath: '/settings/contacts/views'
      preLoaderRoute: typeof SettingsContactsViewsRouteImport
      parentRoute: typeof SettingsContactsRouteRoute
    }
    '/settings/organizations/': {
      id: '/settings/organizations/'
      path: '/'
      fullPath: '/settings/organizations/'
      preLoaderRoute: typeof SettingsOrganizationsIndexRouteImport
      parentRoute: typeof SettingsOrganizationsRouteRoute
    }
    '/settings/organizations/attributes': {
      id: '/settings/organizations/attributes'
      path: '/attributes'
      fullPath: '/settings/organizations/attributes'
      preLoaderRoute: typeof SettingsOrganizationsAttributesRouteImport
      parentRoute: typeof SettingsOrganizationsRouteRoute
    }
    '/settings/organizations/views': {
      id: '/settings/organizations/views'
      path: '/views'
      fullPath: '/settings/organizations/views'
      preLoaderRoute: typeof SettingsOrganizationsViewsRouteImport
      parentRoute: typeof SettingsOrganizationsRouteRoute
    }
  }
}

interface ContactsRouteRouteChildren {
  ContactsIdRoute: typeof ContactsIdRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
}

const ContactsRouteRouteChildren: ContactsRouteRouteChildren = {
  ContactsIdRoute: ContactsIdRoute,
  ContactsIndexRoute: ContactsIndexRoute,
}

const ContactsRouteRouteWithChildren = ContactsRouteRoute._addFileChildren(
  ContactsRouteRouteChildren,
)

interface OrganizationsRouteRouteChildren {
  OrganizationsIdRoute: typeof OrganizationsIdRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
}

const OrganizationsRouteRouteChildren: OrganizationsRouteRouteChildren = {
  OrganizationsIdRoute: OrganizationsIdRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
}

const OrganizationsRouteRouteWithChildren =
  OrganizationsRouteRoute._addFileChildren(OrganizationsRouteRouteChildren)

interface SettingsContactsRouteRouteChildren {
  SettingsContactsAttributesRoute: typeof SettingsContactsAttributesRoute
  SettingsContactsViewsRoute: typeof SettingsContactsViewsRoute
  SettingsContactsIndexRoute: typeof SettingsContactsIndexRoute
}

const SettingsContactsRouteRouteChildren: SettingsContactsRouteRouteChildren = {
  SettingsContactsAttributesRoute: SettingsContactsAttributesRoute,
  SettingsContactsViewsRoute: SettingsContactsViewsRoute,
  SettingsContactsIndexRoute: SettingsContactsIndexRoute,
}

const SettingsContactsRouteRouteWithChildren =
  SettingsContactsRouteRoute._addFileChildren(
    SettingsContactsRouteRouteChildren,
  )

interface SettingsOrganizationsRouteRouteChildren {
  SettingsOrganizationsAttributesRoute: typeof SettingsOrganizationsAttributesRoute
  SettingsOrganizationsViewsRoute: typeof SettingsOrganizationsViewsRoute
  SettingsOrganizationsIndexRoute: typeof SettingsOrganizationsIndexRoute
}

const SettingsOrganizationsRouteRouteChildren: SettingsOrganizationsRouteRouteChildren =
  {
    SettingsOrganizationsAttributesRoute: SettingsOrganizationsAttributesRoute,
    SettingsOrganizationsViewsRoute: SettingsOrganizationsViewsRoute,
    SettingsOrganizationsIndexRoute: SettingsOrganizationsIndexRoute,
  }

const SettingsOrganizationsRouteRouteWithChildren =
  SettingsOrganizationsRouteRoute._addFileChildren(
    SettingsOrganizationsRouteRouteChildren,
  )

interface SettingsRouteRouteChildren {
  SettingsContactsRouteRoute: typeof SettingsContactsRouteRouteWithChildren
  SettingsOrganizationsRouteRoute: typeof SettingsOrganizationsRouteRouteWithChildren
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsContactsRouteRoute: SettingsContactsRouteRouteWithChildren,
  SettingsOrganizationsRouteRoute: SettingsOrganizationsRouteRouteWithChildren,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRouteRoute: ContactsRouteRouteWithChildren,
  OrganizationsRouteRoute: OrganizationsRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  FollowUpsRoute: FollowUpsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
